const femaleNames = [
  "Vera",
  "Penelope",
  "Ikara",
  "Saskia",
  "Pantera",
  "Abigail",
  "Ada",
  "Abbie",
  "Adaline",
  "Adara",
  "Adelice",
  "Adele",
  "Adena",
  "Adrienne",
  "Ailene",
  "Aimee",
  "Ainslee",
  "Ainsley",
  "Alaine",
  "Alana",
  "Alberta",
  "Albertine",
  "Alessandra",
  "Alethea",
  "Alex",
  "Alexa",
  "Alexandra",
  "Alexandria",
  "Alexia",
  "Alexis",
  "Alice",
  "Alison",
  "Aline",
  "Alisun",
  "Aliza",
  "Allegra",
  "Alma",
  "Allyson",
  "Alta",
  "Alvina",
  "Alysia",
  "Alyse",
  "Amalee",
  "Alysse",
  "Amalie",
  "Amelie",
  "Amara",
  "Amber",
  "Amberly",
  "Ana",
  "Anabel",
  "Annabelle",
  "Analiese",
  "Analise",
  "Anastasia",
  "Anastassia",
  "Anatola",
  "Andra",
  "Andrea",
  "Andris",
  "Annette",
  "Angele",
  "Angelia",
  "Angelica",
  "Angelique",
  "Angelina",
  "Anissa",
  "Anselma",
  "Ainsley",
  "Antoinette",
  "Antonia",
  "Anatola",
  "Antonina",
  "Anya",
  "Arya",
  "Arabelle",
  "Arabethe",
  "Arabeth",
  "Artemis",
  "Arlette",
  "Aeris",
  "Aerys",
  "Astra",
  "Astrid",
  "Astrix",
  "Athena",
  "Athene",
  "Audra",
  "Ashil",
  "Augusta",
  "Augustine",
  "Aurelie",
  "Austine",
  "Aveline",
  "Averyl",
  "Avie",
  "Azusa",
  "Azora",
  "Bambie",
  "Bambi",
  "Bethesda",
  "Breatrix",
  "Beatrice",
  "Beatriz",
  "Basia",
  "Belle",
  "Bellina",
  "Benedetta",
  "Benetta",
  "Bernadette",
  "Bethany",
  "Bethanie",
  "Bettina",
  "Blanche",
  "Blisse",
  "Blithe",
  "Blondette",
  "Blythe",
  "Blaire",
  "Bria",
  "Bridgette",
  "Bridgitte",
  "Brita",
  "Brittania",
  "Brynne",
  "Cecilie",
  "Cecile",
  "Cecilia",
  "Cara",
  "Callista",
  "Callie",
  "Calia",
  "Calypso",
  "Cammie",
  "Camila",
  "Camilla",
  "Camille",
  "Cammi",
  "Candace",
  "Candice",
  "Coralie",
  "Corinthe",
  "Corinthia",
  "Caresa",
  "Carena",
  "Caprise",
  "Caressa",
  "Caretta",
  "Carlotta",
  "Carmella",
  "Carma",
  "Carmelice",
  "Carmen",
  "Carmina",
  "Carryth",
  "Corynth",
  "Cass",
  "Cassandra",
  "Kassandra",
  "Catarina",
  "Catriona",
  "Cat",
  "Cecilia",
  "Celeste",
  "Celestia",
  "Celestine",
  "Celia",
  "Celestina",
  "Celina",
  "Celine",
  "Charys",
  "Falon",
  "Panthea",
  "Elwyn",
  "Ophelia",
  "Odelia",
  "Shafira",
  "Odessa",
  "Io",
  "Stella",
  "Vega",
  "Aurora",
  "Aspen",
  "Faye",
  "Fae",
  "Soleil",
  "Terra",
  "Tallulah",
  "Vita",
  "Zara",
  "Dahlia",
  "Willow",
  "Coralie",
  "Genevieve",
  "Evelina",
  "Maeve",
  "Florence",
  "Josephine",
  "Esme",
  "Isabel",
  "Isabella",
  "Lillith",
  "Lilith",
  "Yvonne",
  "Yvette",
  "Imelda",
  "Valda",
  "Juniper",
  "Sloane",
  "Asteria",
  "Solandis",
  "Opaline",
];

const maleNames = [
  "Gideon",
  "Fabian",
  "Grich",
  "Icarus",
  "Gladeus",
  "Ajax",
  "Pascal",
  "Albus",
  "Ambroz",
  "Ezra",
  "Alexios",
  "Caz",
  "Cygnus",
  "Eddard",
  "Jaxon",
  "Nox",
  "Kace",
  "Jayce",
  "Rhaegal",
  "Xanto",
  "Sebastien",
  "Seb",
  "Sebastian",
  "Mandel",
  "Xanther",
  "Gryphon",
  "Leonidas",
  "Deimos",
  "Casper",
  "Malachi",
  "Ulysses",
  "Amadeus",
  "Sirius",
  "Percival",
  "Darcy",
  "Koa",
  "Enzo",
  "Tobias",
  "Xander",
  "Zander",
  "Octavian",
  "Eric",
  "Dusan",
  "Abaddon",
  "Azriel",
  "Darcio",
  "Aleksander",
  "Silas",
  "Caruso",
  "Manthus",
  "Jasper",
  "Philippe",
  "Tyr",
  "Osiris",
  "Bastian",
  "Reese",
  "Tybalt",
  "Nikolas",
  "Nero",
  "Vladimir",
  "Rowan",
];

const lastNames = [
  "Stormborn",
  "Emerson",
  "Jensen",
  "Holloway",
  "Ambrose",
  "Amberhide",
  "Shadowhide",
  "Ambers",
  "Alinac",
  "Belmont",
  "Blackmark",
  "Bellevue",
  "Bertillon",
  "Boudreaux",
  "Bordeaux",
  "Cinderhall",
  "Longfellow",
  "Clawroot",
  "Cinderhell",
  "Coldblight",
  "Chauvet",
  "Clearwater",
  "Dawnless",
  "Deepfellow",
  "Featherly",
  "Strider",
  "Havenly",
  "Keenstone",
  "Brightstone",
  "Lightfoot",
  "Deeprider",
  "Wilder",
  "Wiser",
  "Wisekeeper",
  "Warmane",
  "Brightwood",
  "Katz",
  "Laurier",
  "Viotto",
  "Trevino",
  "Whitlock",
  "Boone",
  "Remington",
  "Duke",
  "Pierce",
  "Steel",
  "Steele",
  "Vandenberg",
  "Webb",
  "Ellis",
  "Presley",
  "Damarys",
  "Luza",
  "Godfrey",
  "Greathouse",
  "Knightley",
  "Princely",
  "Prince",
  "King",
  "Gregorios",
  "Coldshore",
  "Gallus",
  "Ratley",
  "Sevenson",
  "Vita",
  "Darcey",
  "Weston",
  "Bradford",
  "Fitzgerald",
  "Stone",
  "Tennsley",
  "Hanover",
  "Ryder",
  "Atwood",
  "Hamilton",
  "Rowe",
  "Wilkes",
  "Bentley",
  "Claymoore",
  "Brighton",
  "Bailey",
  "Harrington",
  "Larson",
  "Holt",
  "Pierson",
  "Evershire",
  "Crawford",
  "Goodfellow",
  "Harper",
  "Sorrowful",
  "Seaborn",
  "Montero",
  "Stallard",
  "Fleet",
  "Harte",
  "Viotto",
  "La Grange",
  "Bourne",
  "Sisko",
  "Warbelly",
  "Fjord",
  "Chaucer",
  "Benu",
  "Filian",
  "Bryntar",
  "Montague",
];

const ages = [
  "Young Adult",
  "Young Adult",
  "Adult",
  "Adult",
  "Adult",
  "Adult",
  "Middle-Aged",
  "Middle-Aged",
  "Middle-Aged",
  "Elderly",
];

const races = [
  "Dragonborn",
  "Dwarf",
  "Elf",
  "Gnome",
  "Half-Elf",
  "Halfling",
  "Half-Orc",
  "Human",
  "Tiefling",
  "Orc",
  "Leonin",
  "Satyr",
  "Owlin",
  "Aarakocra",
  "Air Genasi",
  "Bugbear",
  "Centaur",
  "Changeling",
  "Deep Gnome",
  "Duergar",
  "Earth Genasi",
  "Eladrin",
  "Fairy",
  "Firbolg",
  "Fire Genasi",
  "Githyanki",
  "Githzerai",
  "Goblin",
  "Goliath",
  "Harengon",
  "Hobgoblin",
  "Kenku",
  "Kobold",
  "Lizardfolk",
  "Minotaur",
  "Sea Elf",
  "Shadar-kai",
  "Shifter",
  "Tabaxi",
  "Tortle",
  "Triton",
  "Water Genasi",
  "Yuan-ti",
  "Aasimar",
  "Kalashtar",
  "Warforged",
];

const jobs = [
  "Academic",
  "Astrologer",
  "Cartographer",
  "Judge",
  "Merchant",
  "Scribe",
  "Scholar",
  "Student",
  "Writer",
  "Poet",
  "Mercenary",
  "Sell-Sword",
  "Bard",
  "Cleric",
  "Fighter",
  "Monk",
  "Wizard",
  "Aristocrat",
  "Duke/Duchess",
  "Count/Countess",
  "Baron/Baroness",
  "Architect",
  "Builder",
  "Carpenter",
  "Stonemason",
  "Glassblower",
  "Artist",
  "Mason",
  "Acolyte",
  "Priest/Priestess",
  "Shaman",
  "Alchemist",
  "Armorer",
  "Baker",
  "Bookkeeper",
  "Pastry Chef",
  "Blacksmith",
  "Brewer",
  "Butcher",
  "Cobbler",
  "Cook",
  "Chef",
  "Dyer",
  "Engraver",
  "Furniture Maker",
  "Goldsmith",
  "Smelter",
  "Jeweler",
  "Instrument Maker",
  "Leatherworker",
  "Locksmith",
  "Criminal",
  "Assassin",
  "Painter",
  "Potter",
  "Skinner",
  "Tanner",
  "Toymaker",
  "Woodcarver",
  "Woodworker",
  "Lumberjack",
  "Weaponsmith",
  "Ship Builder",
  "Weaver",
  "Bandit",
  "Burglar",
  "Pirate",
  "Pickpocket",
  "Jester",
  "Acrobat",
  "Dancer",
  "Thief",
  "Minstrel",
  "Musical Prodigy",
  "Barback/Barmaid",
  "Prostitute",
  "Storyteller",
  "Actor",
  "Playwright",
  "Farmer",
  "Gatherer",
  "Sheep Herder",
  "Horse Trainer",
  "Veterinarian",
  "Hunter",
  "Banker",
  "Tax Collector",
  "Healer",
  "Herbalist",
  "Witch",
  "Midwife",
  "Brothel Keeper",
  "Innkeeper",
  "Tavern Keeper",
  "Beer Merchant",
  "Sommelier",
  "Bookseller",
  "Caravanner",
  "Dairy Seller",
  "Fisher",
  "Florist",
  "Grain Merchant",
  "Grocer",
  "Haberdasher",
  "Livestock Merchant",
  "Horse Breeder",
  "Spice Merchant",
  "Slaver",
  "Clothier",
  "Wine Merchant",
  "Miller",
  "Bounty Hunter",
  "Guard",
  "Soldier",
  "City Guard",
  "Explorer",
  "Sailor",
  "Trapper",
  "Traveler",
  "Diplomat",
  "Politician",
  "Town Crier",
  "Barber",
  "Carriage Driver",
  "Servant",
  "Gardener",
  "Archaeologist",
  "Art Curator",
  "Historian",
  "Sculptor",
  "Slave",
  "Butler",
  "Candlemaker",
  "Beekeeper",
  "Concubine",
  "Gemcutter",
  "Messenger",
  "Knight",
  "Landlord",
  "Singer",
  "Tracker",
  "Lumberjack",
  "Heir/Heiress",
  "Transporter",
  "Outcast",
  "Squire",
  "Guildmaster",
  "Beggar",
  "Looking For Work",
  "Unemployed",
  "Takes Odd Jobs",
];

const sexualOrientation = [
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Straight",
  "Bisexual",
  "Asexual",
  "Gay",
];

const relationshipStatus = [
  "Single",
  "Single",
  "Single",
  "In A Relationship",
  "Recently Broke Up",
  "Single",
  "Married",
  "Recently Divorced",
  "Single",
];

const children = [
  "None",
  "None",
  "None",
  "None",
  "None",
  "None",
  1,
  1,
  2,
  2,
  3,
  4,
];

const appearanceOverall = [
  "is classically beautiful, with a glass-like complexion and a soft, oval face.",
  "has a rather mysterious look. Is he hiding something?",
  "looks a bit sad. I wonder why.",
  "seems to be a very smiley person.",
  "has gorgeous eyes. You'll get lost in them if you're not careful.",
  "is quite pretty, but it isn't distracting.",
  "is rather exotic-looking. You can't help but stare.",
  "is striking in appearance, with a statuesque jawline and strong cheekbones.",
  "has a rather rough appearance.",
  "gives off an intimidating look.",
  "might have some self-esteem issues.",
  "looks to be bright and vivacious.",
  "has a warm and inviting demeanor.",
  "is absolutely ravishing, with sirenesque eyes and angular features.",
  "seems stressed out.",
  "is an unearthly beauty. You've never seen anything like it before.",
  "is a bit ugly, but that's okay.",
  "seems to have a secret.",
  "is definitely hiding something.",
];

const eyeColor = [
  "dark brown",
  "brown",
  "light brown",
  "hazel",
  "green",
  "olive",
  "emerald",
  "grey",
  "light grey",
  "dark grey",
  "amber",
  "hazel",
  "onyx",
  "sapphire",
  "honey",
];

const hairColor = [
  "jet black",
  "black",
  "indigo",
  "dark brown",
  "honey brown",
  "honey blonde",
  "dirty blonde",
  "platinum blonde",
  "white",
  "red",
  "auburn",
  "maroon",
  "chocolate brown",
  "golden blonde",
  "coppery",
  "cool blonde",
  "warm blonde",
  "cool brown",
  "warm brown",
  "violet",
  "pink",
  "pastel blue",
  "pastel pink",
];

const hairStyle = [
  "is kept neatly in a bun.",
  "has a slightly wavy texture.",
  "is pulled into an elegant french twist.",
  "has been buzzed.",
  "is short and wildly sticking up.",
  "looks to never have been washed.",
  "is tightly braided.",
  "is styled in cornrows.",
  "is in a half-pony.",
  "is pulled into a high ponytail.",
  "is held in a loose pony.",
  "is cut at the shoulders.",
  "has a pixie cut.",
  "is long and flowing.",
  "is just incredible. Like.. is this hair even real?",
  "is in two tight french braids.",
  "is held loosely in a top-knot.",
  "has not been brushed in weeks.. or years.",
  "is wild and voluminous.",
  "messily thrown together.",
  "smells vaguely of honey.",
  "has a blunt, asymmetrical cut.",
  "is hidden by a hood.",
  "looks a tad bit greasy.",
  "smells like roses.",
];

const body = [
  "has a fat build.",
  "is quite petite.",
  "is pretty muscular.",
  "has bulging muscles.",
  "is a bit lanky.",
  "looks like a Greek god.",
  "would beat you in a fight.",
  "would definitely lose to you in a fight.",
  "has poor posture.",
  "has excellent posture.",
  "is really, really tall.",
  "is a bit on the short side.",
  "could probably fit in your pocket.",
  "has great legs.",
  "is slightly overweight.",
  "is a bit chubby.",
  "is curvy with a small waist.",
  "has broad shoulders.",
  "has a bit of a beer belly.",
  "looks delicate and frail.",
];

const alignments = [
  "Lawful Good",
  "Lawful Neutral",
  "Lawful Evil",
  "Neutral Good",
  "True Neutral",
  "Neutral Evil",
  "Chaotic Good",
  "Chaotic Neutral",
  "Chaotic Evil",
];

const skins = ["fair", "light", "tan", "medium", "olive", "deep"];

const undertones = [
  "pinkish",
  "blueish",
  "greenish",
  "reddish",
  "purplish",
  "yellowish",
];

const beliefsLG = [
  "Society has merit, and as a participant I defend it.",
  "My Creed is my word, and my hand its upholder.",
  "Though I may disagree, the wisdom of our elders will prevail.",
  "There's nothing like the satisfaction of a made bed and folded laundry.",
];

const beliefsLN = [
  "If I have to save the world, I will.",
  "I am the sword that enforces the will of the people.",
  "Justice is blind.",
  "A vow is a vow. Nothing in this world is worth more.",
];

const beliefsLE = [
  "Come hell or high water, I will hunt those that defy us.",
  "There is no joy greater than seeing the fear in the eyes of those we bring to their knees.",
  "An eye for an eye? If they take my eye, I'll build a beholder out of them and their kin.",
];

const beliefsNG = [
  "The balance must be preserved.",
  "To act in anger is to betray your own judgment.",
  "Protect those who can't defend themselves above all else, then you can do as you will.",
  "Creation and all its imperfections are divine, perversions of it will not be suffered.",
];

const beliefsNN = [
  "Fuck all this shit, man.",
  "Fate controls all things. Who am I to interfere?",
  "...?",
  "Beauty in all things. Right and wrong, good and evil. Respect your ability to indulge in what you please, and do not forget that others have that same privilege.",
];

const beliefsNE = [
  "Take what you can. The only thing you can rely on is yourself.",
  "Allies are great.. but you can find allies anywhere...",
  "We all die alone. I don't care what prayers you say or what family you have. We. All. Die. Alone.",
];

const beliefsCG = [
  "I don't care what you say. This is wrong, and I won't just accept it!",
  "I follow my heart. It tells me what is right and what must be done.",
  "I dunno about all that... but something tells me it's the right thing to do.",
  "Justice is blind and cannot see where mercy and compassion must be exercised.",
];

const beliefsCN = [
  "I do as I please and as I please changes from one day to the next!",
  "The devil is in the details and I care not for reading the fine print.",
  "I was what you would call 'good' once. I have indulged in what you would call a little 'evil' as well. What matters most is the fun that was had all the while!",
];

const beliefsCE = [
  "One man's loss is another's gain.",
  "I stand defiant of those who claim to 'represent' people. People is a term used for animals who cannot act for themselves.",
  "Greed is good.",
  "If it serves me, that's all I need to know.",
];

const personalityTraits = [
  "values friendship and kinship over all.",
  "is typically the life of the party.",
  "wants to be friends with everyone.",
  "is not very careful with words. Makes sure to blurt out every thought and every detail that comes to mind.",
  "has a strong work ethic. Hard work builds character.",
  "means well, but can be disloyal at times. Has tarnished a few friendships this way.",
  "stutters and breaks eye contact when nervous.. which is all of the time.",
  "is hardened to emotion, and rarely shows any form of expression.",
  "is generally quiet and calculated, speaking only when it is important.",
  "can be blunt. Says things as they are without considering others' feelings.",
  "is a pathological liar. I wouldn't count on this one.",
  `is always polite, even if it's disingenuous. But you wouldn't be able to tell.`,
  "is constantly gossiping about something.",
  "trusts strangers way too easily. Easy to manipulate.",
  "can be very arrogant.",
  "spends a little too much time at the brothel.",
  "is difficult to please.",
  "maintains a postitive outlook on life, and is sure to lift everyone's spirits.",
  `can't read or write, but is very sociable and happy to talk to you.`,
  "can be extremely emotional.",
  "is a total animal lover. Would completely replace every human friend with an animal if possible. Wants to save every stray cat, dog, and horse.",
  "is a bit of a troublemaker, and has arrested once or twice.",
  "enjoys stirring drama amongst the townspeople for no good reason.",
  "is generally nice, but can be confrontational. Be careful with this one.",
  "absolutely LOVES, lives, and breathes drama. There is never enough drama for this one.",
  "is always fidgeting around.",
  "is having an affair and doesn't feel guilty about it.",
  "is loved by family and friends alike. A genuinely good person.",
  "has many enemies.",
  "has a strong reputation.",
  "has a terrible reputation.",
  "is always looking for affirmation.",
  "is a conspiracy theorist.",
  "is very religious.",
  "has a soft heart.",
  "may have kleptomaniac tendencies.",
  "is always trying to tell jokes that never land.",
  "is annoyingly sarcastic.",
  "feels society has been corrupted by coin. Tries to barter whenever possible.",
  "has a soft-spot for the downtrodden.",
  "flirts with literally everyone.",
];

const plotHooks = [
  "stumbled upon a curious note by the docks which featured glyphs of various sizes, and seeks to know the origin.",
  "is having an affair with a town guard.",
  "is cursed with lycanthropy and wants to cure it.",
  "has spotted hooded figures entering the neighbor's house every night.",
  "sells potions of questionable origin at the night market for some extra coin.",
  "seeks to die an honorable and glorious death by duel.",
  "is hosting an extravagant Summer soiree for all of the townspeople. You will need an invitation to attend.",
  "has had the same repetitive nightmare for the last month. Could it be more than just a dream?",
  "has heard rumor of a distant land of abundant riches.",
  "has been hired to steal items from the Player Characters.",
  "desperately wants a spouse.",
  "noticed a strong odor emanating from the Northern lake.",
  "wants to run away from home and become a traveling musician.",
  `hates the aristocracy and wants to see them taken down.`,
  "has been infecting townspeople with Lycanthropy.",
  "was framed and wrongly arrested for murder.",
  "wears an amulet engraved with a strange symbol.",
  "has been hired to steal coin from the Player Characters.",
  `wants to invite you to dinner, and won't take "no" for an answer.`,
  "is the host of a deadly disease which is transmitted by physical contact.",
];

export {
  femaleNames,
  maleNames,
  lastNames,
  ages,
  races,
  jobs,
  sexualOrientation,
  relationshipStatus,
  children,
  appearanceOverall,
  eyeColor,
  hairColor,
  hairStyle,
  body,
  alignments,
  skins,
  undertones,
  beliefsLG,
  beliefsLN,
  beliefsLE,
  beliefsNG,
  beliefsNN,
  beliefsNE,
  beliefsCG,
  beliefsCN,
  beliefsCE,
  personalityTraits,
  plotHooks,
};
